GET https://localhost:7210/api/isitwork/authorization
Content-Type: application/json
Accept-Language: ru-RU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhNjFlYzcyOS1hMTg0LTQ2NmYtYThhMy1lMTQ3MDVjYWY3ODIiLCJnaXZlbl9uYW1lIjoi0JTQsNC90LjRj9GAIiwiZmFtaWx5X25hbWUiOiLQlNCw0L3QuNGP0YDQvtCy0LjRhyIsImp0aSI6IjQ1ZWJmZTFhLTE4MmItNDMwNC1iMjM3LWNiZGM3NmVlMTM4NiIsImV4cCI6MTY5ODgzNDg2NCwiaXNzIjoiWFdlYXIuQXBpIiwiYXVkIjoiWFdlYXIuV2ViIn0.ew-_98B8QaLLP2jx7ZLTlEv6JDzgDi1Zc9bcWOdaY4A