GET https://localhost:7210/api/isitwork/authorization
Content-Type: application/json
Accept-Language: ru-RU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDE2NTdmZS0zZTE3LTRlMzUtOTRkMS03YTBlMmU5OTdiOTIiLCJnaXZlbl9uYW1lIjoi0JTQsNC90LjRj9GAIiwiZmFtaWx5X25hbWUiOiLQlNCw0L3QuNGP0YDQvtCy0LjRhyIsImp0aSI6ImNjZGZjNTk1LTE3YTEtNDBkYS05MjljLWE4YjNkMjk5NDEzNiIsImV4cCI6MTY5ODc5ODI0MSwiaXNzIjoiWFdlYXIuQXBpIiwiYXVkIjoiWFdlYXIuV2ViIn0.DpJIXKgkkdKSR60ibLPoRE68htMxkYEr97S1dYrbot8