GET https://5zht445t-7210.inc1.devtunnels.ms/api/account
Content-Type: application/json
Accept-Language: ru-RU
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTg3MTdkOS01NzllLTQyNTQtOTEwNC0wMmFhZWY5NzI0ODgiLCJnaXZlbl9uYW1lIjoidGVzdCIsImZhbWlseV9uYW1lIjoidXNlciIsImp0aSI6IjQxY2YwODkxLTU5ZTMtNDkxYS04ZDA2LTM5NmIxMmM2ODg0YiIsImV4cCI6MTY5ODgzODc1NywiaXNzIjoiWFdlYXIuQXBpIiwiYXVkIjoiWFdlYXIuV2ViIn0.j88k_IkHWAYc3VokfrVBxiIfzGH1P6U2oIDByG3b95Q