PUT https://5zht445t-7210.inc1.devtunnels.ms/api/account/update
Content-Type: application/json
Accept: application/json
Accept-Language: ru-RU
Authorization: Bearer {your_token}

{
	"firstName": "testtest",
	"lastName": "user",
	"email": "testuser1@test.com",
	"phone": "+9967051111111"
}